version: "3.8"

x-common-variables: &common-variables

services:
  mysql_db:
    platform: linux/amd64
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost

  api:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: "./api"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      PORT: 3001
      HOST: 0.0.0.0
      DB_HOSTIP: mysql_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: todo
    ports:
      - "9901:3001"

  client:
    platform: linux/amd64
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://api:3001
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
